### ISSUE TITLE
 transaction input signature script is larger than the max allowed size

### ISSUE THREAD

**Issue by aqui1991** [WikiLeaksFreedomForce/local-blockchain-parser#6]
parsing block file C:\Users\ylplm\AppData\Roaming\bitcoin\blocks\blk00975.dat
readScript: transaction input signature script is larger than the max allowed size [count 8653327013092091391, max 33554432]

**Comment by aqui1991** [comment]
v0.2.1

**Comment by spooktheducks** [comment]
Unfortunately I wrote this code prior to Segwit.  The error is probably because Segwit changed the transaction format.  I have no plans to continue work on this repo, but I'm willing to accept pull requests.
