### ISSUE TITLE
Transaction input signature script is larger than the max allowed size

### ISSUE THREAD

**Issue by swayll** [WikiLeaksFreedomForce/local-blockchain-parser#7]
Problem with parsing **blk01851.dat**
`readScript: transaction input signature script is larger than the max allowed size [count 32768001023, max 33554432]`

**Comment by johannesmols** [comment]
I'm having the same issue. The problem appears first 2017-08-24, which is when SegWit was activated. Seems like this project doesn't support SegWit, and is therefore unusable in its current state. Unfortunate, I would have liked to do some specific things with it.
